apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: redis-service
  name: redis-service
  namespace: dev-glpi
spec:
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
  type: NodePort
status:
  loadBalancer: {}