apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: glpi-db
  name: glpi-db
  namespace: dev-glpi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: glpi-db
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: glpi-db
    spec:
      containers:
      - image: mariadb:10.7
        name: glpi-db
        resources: {}
        ports:
        - containerPort: 3306
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: mariadb-root-password
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: mariadb-password
        - name: MARIADB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mariadb-config
              key: db
        - name: MARIADB_USER
          valueFrom:
            configMapKeyRef:
              name: mariadb-config
              key: user
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mariadb-storage
      volumes:
      - name: mariadb-storage
        hostPath:
          path: /data/mariadb
status: {}