apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mariadb-service
  name: mariadb-service
  namespace: dev-glpi
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: glpi-db
  type: ClusterIP
status:
  loadBalancer: {}