apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: glpi-app
  name: glpi-app
  namespace: dev-glpi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: glpi-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: glpi-app
    spec:
      containers:
      - image: abrantedevops/glpi_nginx:latest
        name: glpi-app
        resources: {}
        ports:
        - containerPort: 80
        - containerPort: 443
        env:
        - name: TIMEZONE
          value: America/Sao_Paulo
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: redis-config
              key: host
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: redis-password
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: redis-config
              key: port
        - name: MARIADB_HOST
          valueFrom:
            configMapKeyRef:
              name: glpi-config
              key: host
        volumeMounts:
        - mountPath: /var/www/html/glpi
          name: glpi-storage
        - mountPath: /etc/timezone
          name: timezone
          readOnly: true
        - mountPath: /etc/localtime
          name: localtime
          readOnly: true
      volumes:
      - name: glpi-storage
        hostPath:
          path: /data/glpi
      - name: timezone
        hostPath:
          path: /etc/timezone
      - name: localtime
        hostPath:
          path: /etc/localtime
status: {}